package com.weiziplus.springboot.models.VO.place;

/**
 * @author 1
 */
public class PlaceVo {
    private Integer weekO;
    private Integer weekS;
    private Integer weekT;
    private Integer weekF;
    private Integer yearO;
    private Integer yearS;
    private Integer yearT;
    private Integer yearF;
    private Double sumSales1dO;
    private Double sumSales1dS;
    private Double sumSales1dT;
    private Double sumSales1dF;
    private Double rateCostO;
    private Double rateCostS;
    private Double rateCostT;
    private Double rateCostF;
    private Double sumAttributedSales1dO;
    private Double sumAttributedSales1dS;
    private Double sumAttributedSales1dT;
    private Double sumAttributedSales1dF;
    private Double sumCostO;
    private Double sumCostS;
    private Double sumCostT;
    private Double sumCostF;
    private Integer sumImpressionsO;
    private Integer sumImpressionsS;
    private Integer sumImpressionsT;
    private Integer sumImpressionsF;
    private Double clicksCostO;
    private Double clicksCostS;
    private Double clicksCostT;
    private Double clicksCostF;
    private Integer sumClicksO;
    private Integer sumClicksS;
    private Integer sumClicksT;
    private Integer sumClicksF;
    private Double rateClicksO;
    private Double rateClicksS;
    private Double rateClicksT;
    private Double rateClicksF;
    private Double rateAttributedSales1dO;
    private Double rateAttributedSales1dS;
    private Double rateAttributedSales1dT;
    private Double rateAttributedSales1dF;
    private String placement;

    public PlaceVo() {
        this.sumSales1dO = 0.0;
        this.sumSales1dS = 0.0;
        this.sumSales1dT = 0.0;
        this.sumSales1dF = 0.0;
        this.rateCostO = 0.0;
        this.rateCostS = 0.0;
        this.rateCostT = 0.0;
        this.rateCostF = 0.0;
        this.sumAttributedSales1dO = 0.0;
        this.sumAttributedSales1dS = 0.0;
        this.sumAttributedSales1dT = 0.0;
        this.sumAttributedSales1dF = 0.0;
        this.sumCostO = 0.0;
        this.sumCostS = 0.0;
        this.sumCostT = 0.0;
        this.sumCostF = 0.0;
        this.sumImpressionsO = 0;
        this.sumImpressionsS = 0;
        this.sumImpressionsT = 0;
        this.sumImpressionsF = 0;
        this.clicksCostO = 0.0;
        this.clicksCostS = 0.0;
        this.clicksCostT = 0.0;
        this.clicksCostF = 0.0;
        this.sumClicksO = 0;
        this.sumClicksS = 0;
        this.sumClicksT = 0;
        this.sumClicksF = 0;
        this.rateClicksO = 0.0;
        this.rateClicksS = 0.0;
        this.rateClicksT = 0.0;
        this.rateClicksF = 0.0;
        this.rateAttributedSales1dO = 0.0;
        this.rateAttributedSales1dS = 0.0;
        this.rateAttributedSales1dT = 0.0;
        this.rateAttributedSales1dF = 0.0;
    }
}
